const mockEvents = {
    city: {
      id: 1007700,
      city: 'München',
      lat: 48.14,
      lon: 11.58,
      state: '',
      country: 'de',
      zip: 'meetup3',
      member_count: 1257
    },
    events: [
      {
        created: 1580186017000,
        duration: 3600000,
        id: '268259064',
        name: 'The Purpose of Life in Buddhism',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1580540400000,
        local_date: '2020-02-01',
        local_time: '08:00',
        updated: 1580186017000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 3,
        group: {
          created: 1449538782000,
          name: 'München Meanings of Life in Buddhism Meetup',
          id: 19192295,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munchen-Meanings-of-Life-in-Buddhism-Meetup',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munchen-Meanings-of-Life-in-Buddhism-Meetup/events/268259064/',
        description: '<p>Why were we born? Why are we living? What is the purpose of our life?<br/>What determines a good fate of happiness, or a bad fate of misfortune?<br/>We will have a Skype session to learn how Buddhism answers to these questions.<br/>If you want to join us, please send your Skype ID to "bobo.yanuar" or by clicking this link: <a href="https://join.skype.com/SWPEaF5Vu6Wk" class="linkified">https://join.skype.com/SWPEaF5Vu6Wk</a><br/>We also have our whatsapp group: <a href="https://chat.whatsapp.com/DnBijHRH4pTFQ7W5ymyPLI" class="linkified">https://chat.whatsapp.com/DnBijHRH4pTFQ7W5ymyPLI</a><br/>If any questions, please contact [masked]<br/>The session will be shared only via Skype</p>',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1579522911000,
        duration: 10800000,
        id: '268057247',
        name: 'Drink&Click™ München, Februar, Froschperspektive',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1581253200000,
        local_date: '2020-02-09',
        local_time: '14:00',
        updated: 1579522911000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 3,
        venue: {
          id: 26820952,
          name: 'Odeonspl. 15',
          lat: 48.1438102722168,
          lon: 11.578198432922363,
          repinned: false,
          address_1: 'Odeonspl. 15',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1540109682000,
          name: 'München Drink&Click™',
          id: 30362257,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munchen-Drink-Click',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munchen-Drink-Click/events/268057247/',
        how_to_find_us: 'Irgendwo im Starbucks oder davor oder dahinter. (Es gibt einen zweiten Eingang zum Hofgarten hin). Du erkennst uns an den Kameras. :-) ',
        description: '<p>Frei übersetzt. Das internationale Thema des Drick &amp; Click weltweit ist "Rat\'s Eye View".</p> <p>Das geht ja fast überall. Dehalb treffen wir uns beim bewährten Starbucks am Hofgarten. Von dort aus haben wir den Hofgarten, die Leopoldstraße die ganze Innenstadt und alles vor der Haustür. Ein paar überdachte öffentliche Orte sind auch nicht weit.</p> <p>Fürs Drink (ab ca. 17 Uhr) nehme ich gern Vorschläge an. Wenn die Gruppe klein bleibt, dann können wir eh spontan entscheiden. Wenn sich mehrere anmelden, dann reserviere ich etwas.<br/>Wegen der möglichen Reservierung die Bitte: SAGE NUR (FEST) ZU, WENN DU AUCH ZUM DRINK/EAT BLEIBST, bzw. nur dafür dazu kommst.</p> <p>Apropos kleine Gruppe: Die Veranstaltung wird neben MeetUp auch auf facebook und in der fotocommunity beworben. Bitte melde Dich nur einmal an und bedenke, dass es auch statt findet, wenn Dein Termin nur wenige Zusagen hat. Wir sind meist so ein halbes Duzend insgesamt, manchmal mehr, manchmal weniger.</p> <p>Für Spätkommer teile ich meinen Standort in unserer WhatsApp-Gruppe. Neue Teilnehmer bekommen den Link zur Gruppe von mir in einer persönlichen Nachricht.</p>',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        local_time: '19:00',
        local_date: '2020-02-11',
        link: 'https://www.meetup.com/Munich-Girl-Gone-International/events/267292966/',
        visibility: 'public_limited',
        group: {
          created: 1380914527000,
          name: 'Munich | Girl Gone International',
          id: 10552542,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munich-Girl-Gone-International',
          who: 'Girls Gone International',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        waitlist_count: 0,
        yes_rsvp_count: 2,
        duration: 7200000,
        time: 1581444000000,
        utc_offset: 3600000,
        name: 'GGI Book Club - February: 84, Charing Cross Road by Helen Hanff',
        id: '267292966'
      },
      {
        local_time: '19:00',
        local_date: '2020-02-05',
        link: 'https://www.meetup.com/munichmingle/events/267915377/',
        visibility: 'public_limited',
        group: {
          created: 1552581049000,
          name: 'Munich Mingle',
          id: 31389319,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'munichmingle',
          who: 'members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        waitlist_count: 0,
        yes_rsvp_count: 5,
        duration: 10800000,
        time: 1580925600000,
        utc_offset: 3600000,
        name: '🎲 Game Night | games provided | 1 free drink',
        id: '267915377'
      },
      {
        created: 1522694856000,
        duration: 10800000,
        id: 'lkgknpybcfbkc',
        name: 'Deutsch-Japanischer\u00ad Stammtisch',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1585332000000,
        local_date: '2020-03-27',
        local_time: '19:00',
        updated: 1522694856000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 2,
        group: {
          created: 1512221367000,
          name: 'Deutsch-Japanischer Stammtisch',
          id: 26763059,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'deutsch-japanischer-stammtisch',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcfbkc/',
        description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. 
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1579299113000,
        duration: 10800000,
        fee: {
          accepts: 'cash',
          amount: 10,
          currency: 'EUR',
          description: '',
          label: 'Price',
          required: false
        },
        id: '268001205',
        name: 'Street Photo Outing II',
        rsvp_limit: 20,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1580563800000,
        local_date: '2020-02-01',
        local_time: '14:30',
        updated: 1579611681000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 17,
        venue: {
          id: 26820928,
          name: 'Schwanthalerstraße 156',
          lat: 48.13792037963867,
          lon: 11.54401969909668,
          repinned: true,
          address_1: 'Schwanthalerstraße 156',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1500930561000,
          name: 'Photography Workshops Munich',
          id: 25119735,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munchen-Photography-Workshops',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munchen-Photography-Workshops/events/268001205/',
        description: '<p>Seid (wieder) herzlich eingeladen zu meinem Foto Workshop zum Thema People And Street Photography - how to get in touch with the people.</p
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1579696976000,
        duration: 4500000,
        fee: {
          accepts: 'paypal',
          amount: 60,
          currency: 'EUR',
          description: '',
          label: 'Price',
          required: true
        },
        id: '268110411',
        name: 'Yoga-Kurs für Einsteiger! 4x75 Min. Basic Vinyasa Flow',
        rsvp_limit: 15,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1586271600000,
        local_date: '2020-04-07',
        local_time: '17:00',
        updated: 1579696976000,
        utc_offset: 7200000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        venue: {
          id: 26589310,
          name: 'Studio 148 - Ausatmen. Einatmen.',
          lat: 48.151973724365234,
          lon: 11.561727523803711,
          repinned: false,
          address_1: 'Theresienstraße 148',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1514739324000,
          name: 'Alpen Yoga München. Yoga, Wandern & Entspannen!',
          id: 27011417,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Alpen-Yoga-Muenchen-Wandern-Yoga-und-Entspannen',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Alpen-Yoga-Muenchen-Wandern-Yoga-und-Entspannen/events/268110411/',
        how_to_find_us: 'Wir sind im oberen Raum',
        description: '<p>Hallo ihr Lieben,<br/>Lust auf Yoga? Komm für 4x75 Min. in den Basic-Kurs für Einsteiger! Damit lernst Du alle Grundlagen, kannst Verspannungen im Körper lösen und Beweglichkeit aufbauen.</p> <p>Daten: April 07. / 14. / 21. / 28.</p> <p>Jetzt hier anmelden!<br/><a href="https://www.re-chargeme.com/angebot/yoga-in-münchen/" class="linkified">https://www.re-chargeme.com/angebot/yoga-in-münchen/</a> oder direkt über Meetup buchen.</p> <p>Ich freu mich auf Dich!<br/>Lena</p> <p>Weitere Infos:<br/>Der Basic Kurs lässt Dich Deinen Körper wieder spüren, unterstützt den Muskelaufbau in Beinen, Rücken, Po und Armen und verbessert die Beweglichkeit der Muskulatur und des Faszienkorsetts. Optimal für Yoga-Einsteiger und Yogis, die es etwas ruhiger angehen möchten.</p> <p>Kursinhalt: Stehhaltungen, Vorbeugen &amp; Hüftöffner, Rückbeugen, Umkehrhaltungen, Meditation, Entspannungsübungen</p> <p>Vorteile für Dich:<br/>- Einfache Übungen mit detaillierter Erklärung<br/>- Vermittlung von Yoga Basiswissen<br/>- 4 Themen-Schwerpunkte</p>',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1580186069000,
        duration: 3600000,
        id: '268259084',
        name: 'The Purpose of Life in Buddhism',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1580626800000,
        local_date: '2020-02-02',
        local_time: '08:00',
        updated: 1580186069000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 3,
        group: {
          created: 1449538782000,
          name: 'München Meanings of Life in Buddhism Meetup',
          id: 19192295,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munchen-Meanings-of-Life-in-Buddhism-Meetup',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munchen-Meanings-of-Life-in-Buddhism-Meetup/events/268259084/',
        description: '<p>Why were we born? Why are we living? What is the purpose of our life?<br/>What determines a good fate of happiness, or a bad fate of misfortune?<br/>We will have a Skype session to learn how Buddhism answers to these questions.<br/>If you want to join us, please send your Skype ID to "bobo.yanuar" or by clicking this link: <a href="https://join.skype.com/SWPEaF5Vu6Wk" class="linkified">https://join.skype.com/SWPEaF5Vu6Wk</a><br/>We also have our whatsapp group: <a href="https://chat.whatsapp.com/DnBijHRH4pTFQ7W5ymyPLI" class="linkified">https://chat.whatsapp.com/DnBijHRH4pTFQ7W5ymyPLI</a><br/>If any questions, please contact [masked]<br/>The session will be shared only via Skype</p>',
        visibility: 'public',
        member_pay_fee: false
      }
    ]
};

export { mockEvents };